version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: zoologiczny_backend
    command: ["python", "main.py"]
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/zoologiczny
      - JWT_SECRET_KEY=your_jwt_secret_key
      - SENDER_EMAIL_ADDRESS=sklepzoologicznyuaim@gmail.com
      - SENDER_EMAIL_PASSWORD=kochamKomandosa123
    depends_on:
        db:
            condition: service_healthy
    volumes:
      - ./backend:/app
      # - ./images:/app/images
    

  db:
    build:
        context: .
        dockerfile: Dockerfile.db
    container_name: zoologiczny_db
    healthcheck:
      test: pg_isready -U postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
 # frontend:
 #   build:
 #     context: ./frontend
 #   container_name: zoologiczny_frontend
 #   ports:
 #     - "3000:3000"
 #   volumes:
 #    - ./frontend/react-app:/app
 #    - ./frontend/react-app/node_modules:/app/node_modules
 #   environment:
 #     NODE_ENV: development
 #   stdin_open: true
 #   tty: true

volumes:
  db_data:
