import os

class Config:
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL', 'postgresql://user:password@0.0.0.0:5432/zoologiczny')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    ACCESS_TOKEN_EXPIRATION_MINUTES = os.getenv('ACCESS_TOKEN_EXPIRATION_MINUTES', 15)
    SENDER_EMAIL_ADDRESS = os.getenv('SENDER_EMAIL_ADDRESS')
    SENDER_EMAIL_PASSWORD = os.getenv('SENDER_EMAIL_PASSWORD')
    CORS_HEADERS = 'Content-Type'
    JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY')